name: Build & Push Scrapzee Images

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service:
          - auth-service
          - dealer-service
          - pricing-service
          - user-service
          - frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set lowercase owner
        run: echo "OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: services/${{ matrix.service }}
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/demo-scrap/scrapzee-${{ matrix.service }}:latest
            ghcr.io/${{ env.OWNER_LOWER }}/demo-scrap/scrapzee-${{ matrix.service }}:${{ github.sha }}
